### ISSUE TITLE
Interest

### ISSUE THREAD

**Issue by o0-o** [ebastler/E80-1800#2]
Hey, I'm interested in this project but have no experience with custom pcbs. Are you planning on having a run of these manufactured? Is that up to someone else? Can I take these plans to someone and have a one-off made? Is it still considered work-in-progress and or is it production-ready?

Would love to get my hands on one. Thanks for all the work on it.

**Comment by ebastler** [comment]
Hey!

I was (and still am) planning to get a batch manufcatured and sell them - Covid and the following chip crysis however hit the market really hard, there's currently no chance to get a reasonable amount (even 1 is already hard) of the chips on this PCB for a decent price (less than 10-20 bucks per chip, they should be ~ 1.5$ MSRP).

Once the market recovers, I'm definitely still planning to do a Groupbuy!

**Comment by o0-o** [comment]
That's great! What can I follow/subscribe/check to be sure I'm notified once you start taking pre-orders?

Also, what would it take to add a split backspace option to the board? I use all compact boards and my muscle memory has the backspace on R2 so I make a lot of \\\\\\ typos on this board. I'd be happy to sponsor that feature if you're open to it (and I can afford it).

**Comment by ebastler** [comment]
I'm currently thinking about creating a discord server, not sure if I'll do that though. My instagram (nick: ebastler) should be useful, if you have instagram. Guess I'll make it a geekhack post too.

**Comment by ebastler** [comment]
In case anyone stumbles upon this: https://discord.gg/VG8xeKzdr7
I actually made a discord server.
