### ISSUE TITLE
Platform not defined

### ISSUE THREAD

**Issue by emrebag** [ebastler/E80-1800#6]
This is the error I get when trying to compile:

$ qmk compile -kb ebastler/E80_1800 -km default
Ψ Compiling keymap with make -r -R -f builddefs/build_keyboard.mk -s KEYBOARD=ebastler/E80_1800 KEYMAP=default KEYBOARD_FILESAFE=ebastler_E80_1800 TARGET=ebastler_E80_1800_default INTERMEDIATE_OUTPUT=.build/obj_ebastler_E80_1800_default VERBOSE=false COLOR=true SILENT=false QMK_BIN="qmk"

☒ Invalid API data: ebastler/E80_1800: keyboard_folder: 'ebastler/E80_1800' does not match '^[0-9a-z][0-9a-z_/]*$'

 *                                                                                                     [ERRORS]

builddefs/build_keyboard.mk:226: *** Platform not defined.  Stop.

**Comment by elpekenin** [comment]
Did you try and look how the folder is actually named?

Hint: `'ebastler/E80_1800' does not match '^[0-9a-z][0-9a-z_/]*$'` reads: uppercase letters are not valid 😉

**Comment by emrebag** [comment]
Yes, I have actually downloaded the whole file from github seperately, renamed it E80_1800 and placed it in the folder, ran the command both way (E80_1800 and E80-1800, still got the same error

**Comment by elpekenin** [comment]
No f*ing idea what you did, but you don't need to download anything manually after setting QMK environment, the keyboard files are already there: <https://github.com/qmk/qmk_firmware/tree/master/keyboards/ebastler/e80_1800>

**Comment by emrebag** [comment]
Bud
I already flashed the via .bin so I am all set
After I got the first error I downloaded the files seperately just to see if something fishy is going on
Just trying to prevent people from having the same issues I did and losing hours

**Comment by elpekenin** [comment]
How exactly is this preventing anything?

You showed an incomplete error message and did not explain how you fixed (or actually, worked around the problem), doesn't seem any useful to me.

**Comment by elpekenin** [comment]
To actually help anyone getting to this

You **dont** want to run `qmk compile -kb ebastler/E80_1800 -km default`, but `qmk compile -kb ebastler/e80_1800 -km default`
Note the lowercase `e`
